@startuml
skin rose
skinparam Linetype ortho
title Диаграмма состояний. Статусы домашнего задания



state Назначено {
  [*] --> Ожидает_начала
}

Ожидает_начала --> В_работе : участник начал выполнять

В_работе --> Отправлено : участник отправил\nрешение на проверку

Отправлено ---> Принято : проверка пройдена
Отправлено --> На_доработке : требуется доработка

На_доработке --> В_работе : участник вносит\nисправления

Принято --> [*] : задание завершено\nуспешно

@enduml
