@startuml
skin rose
title Блок-схема. Работа на лекции

start

while (Лекция продолжается?) is (да)
  :Внимательно слушаем\n     лекцию;

  if (Появился вопрос?) then (нет)
    :Продолжаем слушать\nлекцию;
  else (да)
    :Перейти к процессу\n"Работа с вопросами";
    note right
      См. отдельную диаграмму
      "[[process_questions_activ.puml Работа с вопросами]]"
    end note
  endif

endwhile (нет)

:Лекция завершена;
stop

@enduml