@startuml
skin rose
title Блок-схема. Работа с вопросами во время лекции

start

:Есть ли вопрос?;
if (Есть вопрос?) then (нет)
  :Вопросов нет;
  stop
else (да)
  :Сейчас перерыв\nна вопрос?;
  if (Перерыв на вопрос?) then (нет)
    :Записать вопрос\nв чат;
    stop
  else (да)
    :Поднять руку\nи задать вопрос\nголосом;

    if (Вопрос касается\nтемы лекции?) then (да)
      if (Ответ будет\nдальше в лекции?) then (да)
        :Подвешиваем вопрос\nдо момента объяснения;
        stop
      else (нет)
        :Группа может\nсама ответить?;
        if (Да) then (да)
          :Задать вопрос\nгруппе;
          :Группа отвечает;
          stop
        else (нет)
          :Отвечает ведущий;
          stop
        endif
      endif
    else (нет)
      :Подвешиваем вопрос,\nобсуждаем после лекции;
      stop
    endif
  endif
endif

@enduml