@startuml
skin rose
title "Работа на лекции"

actor "Участник"  as A
actor "Ведущий"  as B
actor "Группа"   as G
participant "Доска Miro" as M

autonumber

' Старт лекции
B -> A: Приветствие, правила лекции
B -> G: Озвучить план занятия

loop Внимательно слушаем лекцию
  B -> A: Объяснение материала
  B -> G: Примеры, вопросы группе

  alt У участника появился вопрос
    A -> B: Поднять руку, попросить слово

    ' Вставляем ранее проработанный блок
    ref over A, B, G, M : (см. отдельную диаграмму \n [[process_questions_activ.puml Работа с вопросами]] )
  else Вопросов нет
    A -> B: Продолжаем слушать
  end
end

' Завершение лекции
B -> G: Подвести итоги
B -> A: Ответить на оставшиеся вопросы
B -> M: Зафиксировать важные вопросы\nи договорённости

@enduml
