@startuml
skin rose
actor Ведущий
actor Участники
autonumber
title Синхронное вежливое общение
' Начало синхронного блока
activate Ведущий
Ведущий -> Участники: Задает вопрос
deactivate Ведущий
activate Участники
Участники -> Участники: Думают над вопросом
Участники -> Ведущий: Отвечают на вопрос
deactivate Участники
activate Ведущий
Ведущий -> Участники: Даёт комментарий / уточнение
deactivate Ведущий

@enduml