@startmindmap
* Обучаем Серегу архитектуре
** диаграммы
***  [[https://c4model.com/ С4]]
*** UML
**** [[https://www.planttext.com/ PlantUML ]]
***** [[https://www.planttext.com/ Полезные материалы ]]
** MIRO
** Применяем на практике

@endmindmap